---  
# This file describes the connection parameters to the evcc instances
# The surplus distributor later tries to connect to those endpoints
EEGMembers:
  - ID: 0
    Username: Berni
    Evcc_Host: 127.0.0.1
    Evcc_Port: 7000
    Evcc_StatePath: /api/state
  - ID: 1
    Username: Muhammed
    Evcc_Host: 127.0.0.1
    Evcc_Port: 7001
    Evcc_StatePath: /api/state

